---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- name: '1'
  type: file
  config:
    maxSize: 64
  label: '1'
- type: text
  name: title
  label: Title
  config:
    required: true
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
pages:
- projects/3d-graff.md
- projects/blue-chair.md
- projects/chelsea-landmark.md
- projects/ios-concept.md
- projects/sunk.md
